# fly.toml app configuration file generated for poliplanner on 2026-08-04T14:24:06-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'poliplanner'
primary_region = 'gru'

[build]
  [build.args]
    GO_VERSION = '1.24.0'

[deploy]
  strategy = 'immediate'

[env]
  APP_BASE_DIR = '/var/poliplanner'
  APP_ENV = 'prod'
  DATABASE_URL = '/poliplanner/poliplanner.db'
  SERVER_ADDR = ':8080'

[[mounts]]
  source = 'poliplanner'
  destination = '/poliplanner'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '256mb'
  cpus = 1
  memory_mb = 256
